/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelListener;
import java.awt.geom.AffineTransform;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author tiaraannisa
 */
public class MainFrame extends javax.swing.JFrame implements View {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        open.setLineWrap(true);
        open.setEditable(false);
        close.setEditable(false);
        close.setLineWrap(true);
        timeExecution.setText("");
//        mPanel = (MyPanel) jShow;
//        jLabel2.set
//        Graphics2D g2 = (Graphics2D) jShow.getGraphics();
//        int w = 1080;// real width of canvas
//        int h = 710;  // real height of canvas
//        // Translate used to make sure scale is centered
//        g2.translate(w / 2, h / 2);
//        g2.scale(2, 2);
//        g2.translate(-w / 2, -h / 2);
//        jShow.paintComponents(g2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSource = new javax.swing.JComboBox();
        jDestination = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        close = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        open = new javax.swing.JTextArea();
        dButton = new javax.swing.JButton();
        fwButton = new javax.swing.JButton();
        bfButton = new javax.swing.JButton();
        jShow = new javax.swing.JPanel();
        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        right = new javax.swing.JButton();
        circle = new javax.swing.JButton();
        left = new javax.swing.JButton();
        zoomIn = new javax.swing.JButton();
        zoomOut = new javax.swing.JButton();
        timeExecution = new javax.swing.JLabel();
        astar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        zValue = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        twoD = new javax.swing.JButton();
        threeD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Start Point -", "IF1.01.01", "IF1.01.02", "IF1.01.03", "IF1.01.04", "IF1.01.05", "IF1.01.06", "IF1.01.07", "IF1.01.08", "IF1.01.09", "IF1.01.10", "IF1.02.01", "IF1.02.02", "IF1.02.03", "IF1.02.04", "IF1.02.05", "IF1.02.06", "IF1.02.07", "IF1.02.08", "IF1.02.09", "IF1.02.10", "IF1.02.11", "IF1.03.01", "IF1.03.02", "IF1.03.03", "IF1.03.04", "IF1.03.05", "IF1.03.08", "IF1.03.10", "IF1.03.11", "IF1.03.12", "IF1.03.14", "IF1.03.15", "IF2.01.01", "IF2.01.02", "IF2.01.03", "IF2.01.04", "IF2.01.05", "IF2.01.06", "IF2.01.07", "IF2.01.08", "IF2.01.09", "IF2.01.10", "IF2.02.01", "IF2.02.02", "IF2.02.03", "IF2.02.04", "IF2.02.05", "IF2.02.06", "IF2.02.07", "IF2.02.08", "IF2.02.09", "IF2.03.01", "IF2.03.02", "IF2.03.03", "IF2.03.04", "IF2.03.05", "IF2.03.06", "IF2.03.07", "IF2.03.08", "IF3.01.01", "IF3.01.02", "IF3.01.03", "IF3.01.04", "IF3.01.05", "IF3.01.06", "IF3.01.07", "IF3.01.08", "IF3.02.01", "IF3.02.02", "IF3.02.03", "IF3.02.05", "IF3.02.06", "IF3.02.07", "IF3.02.08", "IF3.02.10", "IF3.02.11", "IF3.03.01", "IF3.03.02", "IF3.03.03", "IF3.03.04", "IF3.03.05", "IF3.03.06", "IF3.03.07", " " }));
        jPanel1.add(jSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, -1));

        jDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Destination Point -", "IF1.01.01", "IF1.01.02", "IF1.01.03", "IF1.01.04", "IF1.01.05", "IF1.01.06", "IF1.01.07", "IF1.01.08", "IF1.01.09", "IF1.01.10", "IF1.02.01", "IF1.02.02", "IF1.02.03", "IF1.02.04", "IF1.02.05", "IF1.02.06", "IF1.02.07", "IF1.02.08", "IF1.02.09", "IF1.02.10", "IF1.02.11", "IF1.03.01", "IF1.03.02", "IF1.03.03", "IF1.03.04", "IF1.03.05", "IF1.03.08", "IF1.03.10", "IF1.03.11", "IF1.03.12", "IF1.03.14", "IF1.03.15", "IF2.01.01", "IF2.01.02", "IF2.01.03", "IF2.01.04", "IF2.01.05", "IF2.01.06", "IF2.01.07", "IF2.01.08", "IF2.01.09", "IF2.01.10", "IF2.02.01", "IF2.02.02", "IF2.02.03", "IF2.02.04", "IF2.02.05", "IF2.02.06", "IF2.02.07", "IF2.02.08", "IF2.02.09", "IF2.03.01", "IF2.03.02", "IF2.03.03", "IF2.03.04", "IF2.03.05", "IF2.03.06", "IF2.03.07", "IF2.03.08", "IF3.01.01", "IF3.01.02", "IF3.01.03", "IF3.01.04", "IF3.01.05", "IF3.01.06", "IF3.01.07", "IF3.01.08", "IF3.02.01", "IF3.02.02", "IF3.02.03", "IF3.02.05", "IF3.02.06", "IF3.02.07", "IF3.02.08", "IF3.02.10", "IF3.02.11", "IF3.03.01", "IF3.03.02", "IF3.03.03", "IF3.03.04", "IF3.03.05", "IF3.03.06", "IF3.03.07", " " }));
        jPanel1.add(jDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, -1));

        jLabel3.setText("Fully Closed Shortest Path");

        close.setColumns(20);
        close.setRows(5);
        jScrollPane1.setViewportView(close);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 240, 200));

        jLabel1.setFont(new java.awt.Font("Browallia New", 1, 36)); // NOI18N
        jLabel1.setText("TELUR IRIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\egg_60x51.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Shortest Path");

        open.setColumns(20);
        open.setRows(5);
        jScrollPane2.setViewportView(open);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, 190));

        dButton.setText("Dijkstra");
        jPanel1.add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, -1));

        fwButton.setText("Floyd-Warshall");
        jPanel1.add(fwButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        bfButton.setText("Bellman-Ford");
        jPanel1.add(bfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));

        up.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\up.png")); // NOI18N

        down.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\down.png")); // NOI18N

        right.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\right.png")); // NOI18N

        circle.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\circle.png")); // NOI18N

        left.setIcon(new javax.swing.ImageIcon("D:\\!Tiaraaaa\\!BismillahTA\\BismillahTA\\left.png")); // NOI18N

        zoomIn.setText("+");

        zoomOut.setText("-");
        zoomOut.setMaximumSize(new java.awt.Dimension(41, 23));
        zoomOut.setMinimumSize(new java.awt.Dimension(41, 23));

        javax.swing.GroupLayout jShowLayout = new javax.swing.GroupLayout(jShow);
        jShow.setLayout(jShowLayout);
        jShowLayout.setHorizontalGroup(
            jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShowLayout.createSequentialGroup()
                .addContainerGap(941, Short.MAX_VALUE)
                .addGroup(jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jShowLayout.createSequentialGroup()
                        .addGroup(jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jShowLayout.createSequentialGroup()
                                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(up, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jShowLayout.createSequentialGroup()
                        .addComponent(zoomIn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jShowLayout.setVerticalGroup(
            jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zoomOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoomIn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jPanel1.add(jShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 1080, 710));

        timeExecution.setForeground(new java.awt.Color(0, 153, 0));
        timeExecution.setText("time");
        jPanel1.add(timeExecution, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, -1, -1));

        astar.setText("A*");
        jPanel1.add(astar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Graph by Z", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 9))); // NOI18N

        zValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "ALL" }));

        okButton.setText("OK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zValue, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(zValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 75));

        twoD.setText("2D");
        jPanel1.add(twoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, -1));

        threeD.setText("3D");
        jPanel1.add(threeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astar;
    private javax.swing.JButton bfButton;
    private javax.swing.JButton circle;
    private javax.swing.JTextArea close;
    private javax.swing.JButton dButton;
    private javax.swing.JButton down;
    private javax.swing.JButton fwButton;
    private javax.swing.JComboBox jDestination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jShow;
    private javax.swing.JComboBox jSource;
    private javax.swing.JButton left;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea open;
    private javax.swing.JButton right;
    private javax.swing.JButton threeD;
    private javax.swing.JLabel timeExecution;
    private javax.swing.JButton twoD;
    private javax.swing.JButton up;
    private javax.swing.JComboBox zValue;
    private javax.swing.JButton zoomIn;
    private javax.swing.JButton zoomOut;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener al) {
        dButton.addActionListener(al);
        fwButton.addActionListener(al);
        bfButton.addActionListener(al);
        zoomIn.addActionListener(al);
        zoomOut.addActionListener(al);
        astar.addActionListener(al);
        okButton.addActionListener(al);
        up.addActionListener(al);
        down.addActionListener(al);
        left.addActionListener(al);
        right.addActionListener(al);
        circle.addActionListener(al);
        twoD.addActionListener(al);
        threeD.addActionListener(al);
    }

    @Override
    public void addMouseListener(MouseListener ml) {
        jShow.addMouseListener(ml);
        close.addMouseListener(ml);
        open.addMouseListener(ml);
//        jScrollPane3.addMouseListener(ml);
        jShow.addMouseMotionListener(doScrollRectToVisible);
        
    }

    @Override
    public void viewErrorMsg(String errorMsg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JComboBox getjDestination() {
        return jDestination;
    }

    public JPanel getjShow() {
        return jShow;
    }

    public JComboBox getjSource() {
        return jSource;
    }

    public JTextArea getOpen() {
        return open;
    }

    public JTextArea getClose() {
        return close;
    }

    public JButton getBfButton() {
        return bfButton;
    }

    public JButton getdButton() {
        return dButton;
    }

    public JButton getFwButton() {
        return fwButton;
    }

    public JLabel getTimeExecution() {
        return timeExecution;
    }

    public Component getJShowComponent() {
        return jShow.getComponent(0);
    }

//    public JScrollPane getjScrollPane3() {
//        return jScrollPane3;
//    }

    public JButton getZoomIn() {
        return zoomIn;
    }

    public JButton getZoomOut() {
        return zoomOut;
    }

    public JButton getAstar() {
        return astar;
    }

    public JButton getOkButton() {
        return okButton;
    }

    public JComboBox getzValue() {
        return zValue;
    }

    public JButton getCircle() {
        return circle;
    }

    public JButton getDown() {
        return down;
    }

    public JButton getLeft() {
        return left;
    }

    public JButton getRight() {
        return right;
    }

    public JButton getUp() {
        return up;
    }

    public JButton getThreeD() {
        return threeD;
    }

    public JButton getTwoD() {
        return twoD;
    }

    
    
    public void reset() {
        open.setText("");
        close.setText("");
//        jShow.removeAll();
    }

    private AffineTransform m_zoom;
    private Double m_scale;

    public void paintComponent(Graphics p_g) {             // Let UI delegate paint first              // (including background filling, if I'm opaque)   

        if (jShow != null) {
            m_zoom = ((Graphics2D) p_g).getTransform();
            m_zoom.scale(m_scale, m_scale);
            ((Graphics2D) p_g).transform(m_zoom);

            jShow.paintComponents(p_g);
        }
        p_g.dispose();
    }

    public void setScale(double p_newScale) {
        m_scale = p_newScale;
        int width = (int) (getWidth() * m_scale);
        int height = (int) (getHeight() * m_scale);
        setPreferredSize(new Dimension(width, height));
        repaint();
        revalidate();
    }
    MouseMotionListener doScrollRectToVisible = new MouseMotionAdapter() {
        public void mouseDragged(MouseEvent e) {
            Rectangle r = new Rectangle(e.getX(), e.getY(), 1, 1);
            ((JPanel) e.getSource()).scrollRectToVisible(r);
        }
    };

}
